### PR TITLE
CERD-218 > Create module import maps

### PR DESCRIPTION
**Pull request by drochgenius**
Automate the creation of module import maps for all packages.

### CODE REVIEW

**Comment by drochgenius** [comment]
Good morning @adjamenhmh , @chrisunl , could you please take a minute to review this PR from last Friday?

**Comment by drochgenius** [comment]
That's a good catch!
Actually, something I broke accidentally in the server

**Comment by drochgenius** [comment]
Hi @chrisunl , fixed here: ae1eeb911209e4cbb865d121459a07423a9904e8

**Comment by drochgenius** [comment]
Hi @chrisunl , fixed now.
Please retry.
This means updating the package `@hmh/nodejs-base-server` to the latest version.

**Comment by chrisunl** [comment]
ok, works now.

**Pull request merged**
